### ISSUE TITLE
[Regression] ZOCP does not close down cleanly

### ISSUE THREAD

**Issue by fieldOfView** [z25/pyZOCP#57]
Since the "refactor of ZBeacon to ZActor class" in Pyre (https://github.com/zeromq/pyre/commit/1a1b1b0042804ee3dc7183043d3e39c3a67a137c), closing the ZOCP node in the Node Editor (and possibly other examples) results in an error.
```
Traceback (most recent call last):
  File "zne.py", line 243, in onZOCPEvent
    self.zocp.run_once(0)
  File "/home/aldo/Documents/z25/pyZOCP/src/zocp.py", line 792, in run_once
    self.get_message()
  File "/home/aldo/Documents/z25/pyZOCP/src/zocp.py", line 538, in get_message
    peer = uuid.UUID(bytes=msg.pop(0))
  File "/usr/lib/python3.4/uuid.py", line 148, in __init__
    raise ValueError('bytes is not a 16-char string')
```

**Comment by fieldOfView** [comment]
It looks like the STOP message adds a peer id as a hex string as opposed to a 16-char string, so this is probably a Pyre bug.
