### ISSUE TITLE
Key error on exit

### ISSUE THREAD

**Issue by sphaero** [z25/pyZOCP#70]
Can't copy paste but it is at:
self.on_peer_exit
nd = self.znodes.pop(peer)
KeyError: UUID('273642....

**Comment by sphaero** [comment]
ow urwZOCP.py line 741

**Comment by sphaero** [comment]
Is this related?
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 696, in <lambda>
    func_fdtransform = lambda _, cond, data: func(channel, cond, data)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 631, in <lambda>
    return (lambda a1, a2, data: callback(a1, a2, *data), user_data)
  File "zvideoplayer.py", line 193, in zocp_handle
    self.run_once()
  File "/usr/local/lib/python3.2/dist-packages/zocp/zocp.py", line 792, in run_once
    self.get_message()
  File "/usr/local/lib/python3.2/dist-packages/zocp/zocp.py", line 560, in get_message
    self.peers_capabilities.pop(peer)
KeyError: UUID('2763ca30-0528-40f6-9975-a6b4b85f1d51')
```

**Comment by sphaero** [comment]
Another one
```
    self._watch_files[fd]()R2 : [0, 0, 0, ome/pi/Screen04_04.m                      [ ] fade            
  File "/home/arnaud/src/pyZOCP/src/zocp.py", line 611, in get_message              [X] auto_next       
    self._handle_SIG(msg[method], peer, name, grp)                                  [X] loop            
  File "/home/arnaud/src/pyZOCP/src/zocp.py", line 748, in _handle_SIG
    self.on_peer_signaled(peer, name, data)
  File "urwZOCP.py", line 763, in on_peer_signaled
    nd[0].original_widget.update()
  File "urwZOCP.py", line 591, in update
    self._update_widgets()
  File "urwZOCP.py", line 623, in _update_widgets
    wgt = urwid.AttrMap(urwid.CheckBox(name, state=val.get('value')), 'options', 'selected')
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 154, in __init__
    self.set_state(state)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 232, in set_state
    repr(self), repr(state)))
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 585, in __repr__
    return split_repr(self)
  File "/usr/lib/python3/dist-packages/urwid/split_repr.py", line 51, in split_repr
    words = self._repr_words()
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 157, in _repr_words
    return self.__super._repr_words() + [
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 589, in _repr_words
    if self.selectable():
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 1753, in <lambda>
    selectable = property(lambda self:get_delegate(self).selectable)
AttributeError: 'NoneType' object has no attribute 'selectable'
```

**Comment by fieldOfView** [comment]
Need a little more info. What were you doing when these errors happened? I cannot reproduce this from the description above.
