### ISSUE TITLE
error on unsubscribe

### ISSUE THREAD

**Issue by sphaero** [z25/pyZOCP#80]
Probably regression
```
Traceback (most recent call last):
  File "painters.py", line 118, in <module>
    test = Painters("Painter")
  File "/home/people/arnaud/src/CreativeConcur/sphof/canvas_actor.py", line 319, in __init__
    super(CanvasActor, self).__init__(*args, **kwargs)
  File "/home/people/arnaud/src/CreativeConcur/sphof/actors.py", line 164, in __init__
    super(LeadActor, self).__init__(*args, **kwargs)
  File "/home/people/arnaud/src/CreativeConcur/sphof/actors.py", line 77, in __init__
    self.start()
  File "/home/people/arnaud/src/CreativeConcur/sphof/actors.py", line 168, in start
    self.run()
  File "/home/people/arnaud/src/CreativeConcur/sphof/actors.py", line 138, in run
    self.run_once(timeout * 1000)   # parse ZOCP queue
  File "/home/people/arnaud/src/pyZOCP/src/zocp.py", line 864, in run_once
    self.get_message()
  File "/home/people/arnaud/src/pyZOCP/src/zocp.py", line 670, in get_message
    self._handle_UNSUB(msg[method], peer, name, grp)
  File "/home/people/arnaud/src/pyZOCP/src/zocp.py", line 764, in _handle_UNSUB
    self.signal_unsubscribe(recv_peer, receiver, emit_peer, emitter)
  File "/home/people/arnaud/src/pyZOCP/src/zocp.py", line 453, in signal_unsubscribe
    if not any(self.subscribers[recv_peer][emitter]):
KeyError: UUID('297a63d7-81c0-4de6-91e4-e66d7c917688')
```

**Comment by sphaero** [comment]
I think this is caused by reverse order arguments as discussed in #82  and in pyZNodeEditor
